### ISSUE TITLE
Normal README?

### ISSUE THREAD

**Issue by awakair** [bit69tream/noterr#1]
How to build it, screenshots, etc...

**Comment by bit69tream** [comment]
It is not yet ready for use. I'll add a proper README after all the essential features are implemented and somewhat polished (if that'll ever happen).

But if you want to build it you can do so by doing:
```sh
$ mkdir build
$ cd build
$ cmake ..
$ cmake --build .
```

And then you'd need to launch it from the project root like that:
```sh
$ build/noterr
```
because that's just how it is right now.

Also, keep in mind that I only ever tested it on linux, so I cannot guarantee you that you'll be able to build and run it on any other operating system.
